---

name: CD
"on":
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  attestations: read

env:
  ZIG_VERSION: 0.13.0

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build
    runs-on: ubuntu-latest
    needs: [release]
    permissions:
      id-token: write
      contents: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86-linux"
          - "x86_64-linux"
          - "aarch64-linux"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} --release=safe
          mv zig-out/bin/xtxf xtxf
          tar -cvf xtxf-${{ matrix.target}}.tar xtxf

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'xtxf'

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh release upload ${{ inputs.tag_name }} \
          xtxf-${{ matrix.target }}.tar

      - name: Verify attestation
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh attestation verify xtxf --owner "$GITHUB_REPOSITORY_OWNER"

  build-macos:
    name: Build
    runs-on: macos-latest
    needs: [release]
    permissions:
      id-token: write
      contents: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86_64-macos"
          - "aarch64-macos"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} --release=safe
          mv zig-out/bin/xtxf xtxf
          tar -cvf xtxf-${{ matrix.target }}.tar xtxf

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'xtxf'

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh release upload ${{ inputs.tag_name }} \
          xtxf-${{ matrix.target }}.tar

      - name: Verify attestation
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh attestation verify xtxf --owner "$GITHUB_REPOSITORY_OWNER"
