---

name: CI
"on": [push, pull_request]

permissions:
  contents: read

env:
  ZIG_VERSION: 0.12.0

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

  lint:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check .

  release:
    needs: [build]
    permissions:
      contents: write
    if: github.repository_owner == 'charlesrocket' && startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/cd.yml
    with:
      tag_name: ${{ github.ref_name }}
      zig_version: ${{ needs.build.outputs.zig_version }}
